version: 2
jobs:
  build:
    docker:
      - image: eddiewebb/php:7.2-apache-intl
      - image: mysql:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: whomai
      - run: php -v
